<h1>Gadget Count</h1>

<div id="datagrid" style="display:none"></div>

<script type="text/javascript">
    $("#datagrid").flexigrid
			(
			{
			url: '/portal/gadgetcount/format/json',
			dataType: 'json',
			colModel : [
				{display: 'Id', name : 'id', width : 40, sortable : true, align: 'center'},
				{display: 'Name', name : 'name', width : 180, sortable : true, align: 'left'}
				],
			buttons : [
				{name: 'Add', bclass: 'add', onpress : test},
				{name: 'Delete', bclass: 'delete', onpress : test},
				{separator: true}
				],
			searchitems : [
				{display: 'Id', name : 'id'},
				{display: 'Name', name : 'name', isdefault: true}
				],
			sortname: "id",
			sortorder: "asc",
			usepager: true,
			singleSelect: true,
			title: 'Persons',
			useRp: true,
			rp: 15,
			showTableToggleBtn: true,
			width: 700,
			height: 200
			}
			);

    function test(com,grid)
			{
				if (com=='Delete')
					{
						confirm('Delete ' + $('.trSelected',grid).length + ' items?')
					}
				else if (com=='Add')
					{
						alert('Add New Item');
					}
			}
</script>
