<?php
/**
 * SURFconext Manage
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext Manage
 * @package
 * @copyright Copyright © 2010-2011 SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */
?>
<style>
    .exportContainer {
        float: left;
        margin-right: 1em;
    }
</style>
<div id="export">
    <h3>Export</h3>
    <form action="<?php echo $this->url(); ?>">
        <?php foreach ($this->exportParameters as $name => $value): ?>
            <input type="hidden" name="<?=$name?>" value="<?=$value?>">
        <?php endforeach; ?>

        <div class="exportContainer">
            <label for="exportEverything">All records</label>
            <input type="checkbox" name="everything" id="exportEverything" />
        </div>

        <div class="exportContainer">
            <label for="exportMonth">Month</label>
            <select id="exportMonth" name="month">
                <option value="01" <?php if (date('m') === "02"): ?> selected="selected"<?php endif; ?>>January</option>
                <option value="02" <?php if (date('m') === "03"): ?> selected="selected"<?php endif; ?>>February</option>
                <option value="03" <?php if (date('m') === "04"): ?> selected="selected"<?php endif; ?>>March</option>
                <option value="04" <?php if (date('m') === "05"): ?> selected="selected"<?php endif; ?>>April</option>
                <option value="05" <?php if (date('m') === "06"): ?> selected="selected"<?php endif; ?>>May</option>
                <option value="06" <?php if (date('m') === "07"): ?> selected="selected"<?php endif; ?>>June</option>
                <option value="07" <?php if (date('m') === "08"): ?> selected="selected"<?php endif; ?>>July</option>
                <option value="08" <?php if (date('m') === "09"): ?> selected="selected"<?php endif; ?>>August</option>
                <option value="09" <?php if (date('m') === "10"): ?> selected="selected"<?php endif; ?>>September</option>
                <option value="10" <?php if (date('m') === "11"): ?> selected="selected"<?php endif; ?>>October</option>
                <option value="11" <?php if (date('m') === "12"): ?> selected="selected"<?php endif; ?>>November</option>
                <option value="12" <?php if (date('m') === "01"): ?> selected="selected"<?php endif; ?>>December</option>
            </select>
        </div>

        <div class="exportContainer">
            <label for="exportYear">Year</label>
            <select id="exportYear" name="year">
                <?php
                $startYear = 2010;
                $currentYear    = (int)date('Y');
                $lastMonthsYear = (int)date('Y', strtotime('last month'));
                $maxYear = $currentYear + 2;
                $year = $startYear;
                while ($year <= $maxYear):
                ?>
                <option value="<?php echo $year; ?>"<?if ($year === $lastMonthsYear): ?> selected="selected"<?php endif; ?>><?php echo $year; ?></option>
                <?php $year++; endwhile; ?>
            </select>
        </div>

        <div class="exportContainer">
            <label for="exportFormat">Format</label>
            <select id="exportFormat" name="format">
                <option value="csv-export">CSV</option>
                <option value="json-export">JSON</option>
            </select>
        </div>

        <div class="exportContainer">
            <label for="exportSubmit">&nbsp;</label>
            <input type="submit" id="exportSubmit" name="export" value="Export" />
        </div>
    </form>
</div>