<?php
/**
 * SURFconext Manage
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext Manage
 * @package
 * @copyright Copyright © 2010-2011 SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */
?>
<div id="export">
    <p><?php echo $this->config->title ?></p>
    <form action="<?php echo $this->config->action ?>">
        <label for="exportEverything">Alles</label>
        <input type="checkbox" name="everything" id="exportEverything"/>
        <label for="exportMonth">Maand</label>
        <select id="exportMonth" name="month">
            <option value="01">Januari</option>
            <option value="02">Februari</option>
            <option value="03">Maart</option>
            <option value="04">April</option>
            <option value="05">Mei</option>
            <option value="06">Juni</option>
            <option value="07">Juli</option>
            <option value="08">Augustus</option>
            <option value="09">September</option>
            <option value="10">Oktober</option>
            <option value="11">November</option>
            <option value="12">December</option>
        </select>
        <label for="exportYear">Jaar</label>
        <select id="exportYear" name="year">
            <option value="2010">2011</option>
            <option value="2011">2012</option>
            <option value="2012">2013</option>
            <option value="2013">2014</option>
        </select>
        <label for="exportFormat">Formaat</label>
        <select id="exportFormat" name="format">
            <option value="csv">CSV</option>
            <option value="text">Tekst</option>
            <option value="json">JSON</option>
        </select>
        <input type="submit" name="export" value="Export" />
    </form>
</div>