<?php
/**
 * SURFconext Manage
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext Manage
 * @package
 * @copyright Copyright © 2010-2011 SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */
?>
<style>
    .exportContainer {
        float: left;
        margin-right: 1em;
    }
</style>
<div id="export">
    <h3>Export</h3>
    <form action="<?php echo $this->url(); ?>">
        <div class="exportContainer">
            <label for="exportEverything">All records</label>
            <input type="checkbox" name="everything" id="exportEverything" />
        </div>

        <div class="exportContainer">
            <label for="exportMonth">Month</label>
            <select id="exportMonth" name="month">
                <option value="01">January</option>
                <option value="02">February</option>
                <option value="03">March</option>
                <option value="04">April</option>
                <option value="05">May</option>
                <option value="06">June</option>
                <option value="07">July</option>
                <option value="08">August</option>
                <option value="09">September</option>
                <option value="10">October</option>
                <option value="11">November</option>
                <option value="12">December</option>
            </select>
        </div>

        <div class="exportContainer">
            <label for="exportYear">Year</label>
            <select id="exportYear" name="year">
                <option value="2010">2010</option>
                <option value="2011">2011</option>
                <option value="2012">2012</option>
                <option value="2013">2013</option>
            </select>
        </div>

        <div class="exportContainer">
            <label for="exportFormat">Format</label>
            <select id="exportFormat" name="format">
                <option value="csv-export">CSV</option>
                <option value="json-export">JSON</option>
            </select>
        </div>

        <div class="exportContainer">
            <label for="exportSubmit">&nbsp;</label>
            <input type="submit" id="exportSubmit" name="export" value="Export" />
        </div>
    </form>
</div>