<?php
    // Format the column config for export to json
    $dataSourceFields = array();
    $columnsDefinition = $this->config->columns->toArray();
    $searchableFields = array();
    foreach ($columnsDefinition as $key => $definition) {
        $dataSourceFields[] = $key;

        if (!isset($definition['hidden']) || !$definition['hidden']) {
            // Add visible fields as columns
            $definition['key'] = $key;
            $columnsDefinition[] = $definition;

            // Register searchable fields.
            if (isset($definition['searchable']) && $definition['searchable']) {
                $searchableFields[] = array(
                    'key' => $key,
                    'label' => $definition['label'],
                );
            }
        }
        unset($columnsDefinition[$key]);
    }
?>

<?php if (!empty($searchableFields)): ?>
<br />
<form id="<?php $this->searchId = 'search'; echo $this->searchId; ?>"
      action=""
      onsubmit="return false;">
    <?php foreach ($searchableFields as $searchableField): ?>
    <label for="search-<?php echo $searchableField['key']; ?>">
        <?php echo $searchableField['label']; ?>
    </label>
    <input id="search-<?php echo $searchableField['key']; ?>"
           data-key="<?php echo $searchableField['key']; ?>"
           type="text"
           size="50" />
    <?php endforeach; ?>
    <br />
    <input type="submit" value="Search" />
</form>
<?php endif; ?>

<div id="<?php $this->id = 'datagrid'; echo $this->id; ?>"></div>

<script type="text/javascript" src="/javascript/coinmanage.ajaxdatatables.js"></script>
<script type="text/javascript" src="/javascript/coinmanage.yui.datatable.formatters.js"></script>
<script type="text/javascript" src="/javascript/coinmanage.yui.datatable.requery.js"></script>
<script type="text/javascript">
COINMANAGE.lastDataTable = COINMANAGE.AjaxDataTable('#<?php echo $this->id; ?>').
    setLoadUrl('<?php echo $this->url(array('format'=>'json'));?>/?').
    setLoadFields(<?php echo json_encode($dataSourceFields); ?>).
    setDisplayColumns(<?php echo json_encode($columnsDefinition); ?>).
<?php if (isset($this->config->editable) && $this->config->editable): ?>
    onRecordClick(function(DataTable) {
        // Some magic to get the id of the row the use selected
        var id = DataTable.getRecord(DataTable.getSelectedRows()[0]).getData('id');
        window.location.href = '<?php echo $this->url($this->config->edit->url->toArray()); ?>?id=' + id;
    }).
<?php endif; ?>
<?php if (isset($this->config->pageSize) && !(isset($this->config->paginate) && !$this->config->paginate)) : ?>
    setLimit(<?php echo $this->config->pageSize; ?>).
<?php endif; ?>
<?php if (isset($this->config->deletable) && $this->config->deletable) : ?>
    addRecordAction('delete', {
        imgAlt: 'delete',
        imgSrc: '/images/icons/delete.png',
        onClick: function(el, record, DataTable) {
            if (!window.confirm('Verwijder rij?')) {
                return false;
            }

            var myDataSource = new YAHOO.util.DataSource(
                '<?php echo $this->url(array('action'=>'delete')); ?>?'
            );
            myDataSource.sendRequest('id=' + record.getData('id'), {
                success : function() {
                    DataTable.reQuery();
                }
            });
            return false;
        }
    }).
<?php endif; ?>
<?php if (isset($this->config->actions) && !empty($this->config->actions)): ?>
    <?php foreach ($this->config->actions as $actionConfig): ?>
    addRecordAction('<?php echo $actionConfig->name;?>', {
        <?php if (isset($actionConfig->imgAlt)): ?>
        "imgAlt": <?php echo json_encode($actionConfig->imgAlt); ?>,
        <?php endif; ?>
        <?php if (isset($actionConfig->imgSrc)): ?>
        "imgSrc": <?php echo json_encode($actionConfig->imgSrc); ?>,
        <?php endif; ?>
        <?php if (isset($actionConfig->title)): ?>
        "title": <?php echo json_encode($actionConfig->title); ?>,
        <?php endif; ?>
        <?php if (isset($actionConfig->url)): ?>
        "href": <?php echo json_encode($this->url($actionConfig->url->toArray())); ?>,
        <?php endif; ?>
        "dummyForTrailingComma": ''
    }).
    <?php endforeach; ?>
<?php endif; ?>
<?php if (isset($this->searchId)): ?>
    registerSearchForm('<?php echo $this->searchId; ?>').
<?php endif; ?>
<?php if (isset($this->config->defaultSortField)): ?>
    setSortedBy('<?php echo $this->config->defaultSortField; ?>').
<?php endif; ?>
<?php if (isset($this->config->defaultSortDir)): ?>
    setSortedDir('<?php echo $this->config->defaultSortDir; ?>').
<?php endif; ?>
    render();
</script>