<div id="<?php $this->id = 'datagrid'; echo $this->id; ?>"></div>

<script type="text/javascript" src="/javascript/coinmanage.ajaxdatatables.js"></script>
<script type="text/javascript" src="/javascript/yui.surfconext.formatters.js"></script>
<script type="text/javascript">
<?php
    // Format the column config for export to json
    $fields = array();
    $columnsDefinition = $this->config->columns->toArray();
    foreach ($columnsDefinition as $key => $definition) {
        $definition['key'] = $key;
        if (!isset($definition->hidden) || $definition->hidden !== true) {
            $fields[] = $key;
        }
        $columnsDefinition[] = $definition;
        unset($columnsDefinition[$key]);
    }
?>

COINMANAGE.AjaxDataTable('#<?php echo $this->id; ?>').
    setLoadUrl('<?php echo $this->url(array('format'=>'json'));?>/?').
    setLoadFields(<?php echo json_encode($fields); ?>).
    setDisplayColumns(<?php echo json_encode($columnsDefinition); ?>).
    onRecordClick(function(DataTable) {
        // Some magic to get the id of the row the use selected
        var id = DataTable.getRecord(DataTable.getSelectedRows()[0]).getData('id');
        window.location.href = '<?php echo $this->url(array('action'=>'edit'))?>?id=' + id;
    }).
<?php if (isset($this->config->pageSize)) : ?>
    setLimit(<?php echo $this->config->pageSize; ?>).
<?php endif; ?>
<?php if (isset($this->config->deletable) && $this->config->deletable) : ?>
    addRecordAction('delete', {
        imgAlt: 'delete',
        imgSrc: '/images/icon_trashcan.gif',
        onClick: function(el, record, DataTable) {
            if (!confirm('Verwijder rij?')) {
                return false;
            }

            var myDataSource = new YAHOO.util.DataSource(
                '<?php echo $this->url(array('action'=>'delete')); ?>?'
            );
            myDataSource.sendRequest('id=' + record.getData('id'), {
                success : function() {
                    window.location.reload();
                }
            });
        }
    }).
<?php endif; ?>
<?php if (isset($this->config->defaultSortField)): ?>
    setSortedBy('<?php echo $this->config->defaultSortField; ?>').
<?php endif; ?>
<?php if (isset($this->config->defaultSortDir)): ?>
    setSortedDir('<?php echo $this->config->defaultSortDir; ?>').
<?php endif; ?>
    render();
</script>