<?php
/**
 * SURFconext Manage
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext Manage
 * @package
 * @copyright Copyright © 2010-2011 SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */
?>
<section id="dashboard">
    <h1>Dashboard</h1>

    <div id="columnContainer" class="hide">
        <div class="column">
            <div class="box">
                <div class="box-header">
                    <h2>Common tasks</h2>
                </div>
                <div class="box-content">
                    <p><button title="Clear EngineBlock -> Service Registry cache"><img src="/media/clear-cache.png" alt="" /></button></p>
                    <hr />
                    <p>The Service Registry is:</p>
                    <ul>
                        <li>
                            <input type="radio" name="service_registry_login" value="federated" id="service_registry_login_federated" checked="checked" />
                            <label for="service_registry_login_federated">Federated</label>
                        </li>
                        <li>
                            <input type="radio" name="service_registry_login" value="password" id="service_registry_login_password" />
                            <label for="service_registry_login_password">Password protected</label>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="box">
                <div class="box-header">
                    <h2>Clear consent</h2>
                </div>
                <div class="box-content">
                    <table>
                        <tr>
                            <td>For IdP</td>
                            <td><select><option>Select an Idp</option><option>Universiteit van Amsterdam</option></select></td>
                        </tr>
                        <tr>
                            <td>For SP</td>
                            <td><select><option>Select a SP</option><option>SURFmedia</option></select></td>
                        </tr>
                        <tr>
                            <td>For user</td>
                            <td><input type="text" /></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><button>Clear ALL consent</button></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="box">
                <div class="box-header">
                    <h2>Admin Status</h2>
                </div>
                <div class="box-content">
                    <div class="component-status-error">GUI</div>
                    <div class="component-status-okay">EngineBlock</div>
                    <div class="component-status-okay">Service Registry (JANUS)</div>
                </div>
            </div>

            <div class="box">
                <div class="box-header">
                    <h2>Logins</h2>
                </div>
                <div class="box-content">
                    <table>
                        <tr>
                            <th>Last successful login</th>
                            <td colspan="2">2 minutes ago</td>
                        </tr>
                        <tr>
                            <th>Today</th>
                            <td class="numeric">397</td>
                        </tr>
                        <tr>
                            <th>Yesterday</th>
                            <td class="numeric">1.500</td>
                        </tr>
                        <tr>
                            <th>This month</th>
                            <td class="numeric">153.908</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

</section>

<section class="hide">
    <h1>Engine Block</h1>

    <h2>Show logs</h2>

    <h2>Sessions</h2>
</section>
