<?php echo $this->doctype() ?>
<html lang="nl">
    <head>
        <meta charset="utf-8" />
        <title>SURFconext Platform Administration Environment</title>
        <?php 
            echo $this->headLink()->appendStylesheet('/css/reset.css')
                                  ->appendStylesheet('/css/fonts.css')
                                  ->appendStylesheet('/css/global.css')
                                  ->appendStylesheet('/css/boxes.css'); 

            echo $this->headScript(); 
            echo $this->headStyle();
        ?>

        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/fonts/fonts.css" />
        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/paginator/assets/skins/sam/paginator.css" />
        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/datatable/assets/skins/sam/datatable.css" />
        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/menu/assets/skins/sam/menu.css" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/yahoo-dom-event/yahoo-dom-event.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/container/container_core.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/menu/menu.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/connection/connection.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/yahoo/yahoo.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/event/event.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/json/json.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/element/element.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/selector/selector.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/datasource/datasource.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/datatable/datatable.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/paginator/paginator.js"></script>

        <!--[if lt IE 9]>
        <script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body class="yui-skin-sam">
        <header>
            <div class="nav" id="TopNav">
                <p class="identity">
                    Ingelogd als:
                    <?php echo($this->identity->displayName); ?>
                </p>
            </div>
            <a href="/" id="Logo">
                <img src="/media/logo-surfnet.gif" alt="SURFNET - We make innovation work">
            </a>
        </header>
        
        <nav>
            <?php echo $this->navigation();?>
        </nav>
        <div class='content yui-skin-sam'>
            <?php echo $this->layout()->content ?>
        </div>
        
        <footer>
            <?php echo $this->inlineScript() ?>
        </footer>
    </body>
</html>
