<?php $model = $this->virtualOrganisation; ?>

<form id="virtualorganisation-edit"
      name="virtualorganisation-edit"
      action="<?php echo $this->saveUrl;?>"
      method="POST">

    <input type="hidden" id="org_vo_id" name="org_vo_id" value="<?php echo $this->escape($model->vo_id); ?>"/>

    <fieldset title="Virtual Organisation Name">
        <?php if (isset($model->errors['vo_id'])): foreach ($model->errors['vo_id'] as $error): ?>
        <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="vo_id">Virtual Organisation id<span class="required-postfix" title="Required field">*</span></label>
        <input id="vo_id"
               name="vo_id"
               type="text"
               value="<?php echo $this->escape($model->vo_id); ?>"
               size="100"
               maxlength="255"
                />

        <p class="hint">
            Only alphanumeric characters, underscores and dashes are allowed.
        </p>
    </fieldset>

    <?php if (!$model->vo_id): ?>
    <fieldset title="Virtual Organisation Type">
        <label>Virtual Organisation type<span class="required-postfix" title="Required field">*</span></label>
        <input id="vo_type_mixed"
               name="vo_type"
               type="radio"
               value="MIXED" <?= $model->vo_type === 'MIXED' ? 'checked' : !isset($model->vo_type) ? 'checked' : ''; ?>>
        Mixed (IDPs & Groups)<br/>

        <input id="vo_type_group"
               name="vo_type"
               type="radio"
               value="GROUP" <?= $model->vo_type === 'GROUP' ? 'checked' : ''; ?>>
        Group<br/>

        <input id="vo_type_stem"
               name="vo_type"
               type="radio"
               value="STEM" <?= $model->vo_type === 'STEM' ? 'checked' : ''; ?>>
        Stem<br/>

        <input id="vo_type_idp"
               name="vo_type"
               type="radio"
               value="IDP" <?= $model->vo_type === 'IDP' ? 'checked' : ''; ?>>
        IdP<br/>
    </fieldset>
    <?php else: ?>
        <input type="hidden" name="vo_type" value="<?=$model->vo_type; ?>">
    <?php endif; ?>

    <?php
    if (strlen($model->vo_id) > 0 && !isset($model->errors['vo_id'])) :
        if (in_array($model->vo_type, array('MIXED', 'GROUP'))) : ?>
            <a href="<?php echo $this->url(array('action' => 'groupadd', 'vo_id' => $model->vo_id)); ?>">
                Add a new Group
            </a>
            <?php
            echo $this->grid($this->gridData['groups']['gridConfig']);
        endif;
        if (in_array($model->vo_type, array('STEM'))): ?>
            <div class="notice">
                <h3>Reminder</h3>
                <ol>
                    <li>Create a stem</li>
                    <li>Create the VO for this stem with the correct naming convention</li>
                </ol>
            </div>
            <br/>
            <p>
                The current stem name is <strong><?= $this->voStem; ?></strong>.
            </p>
            <?php
        endif;
        if (in_array($model->vo_type, array('MIXED', 'IDP'))): ?>
            <a href="<?php echo $this->url(array('action' => 'idpadd', 'vo_id' => $model->vo_id)); ?>">
                Add a new IdP
            </a>
            <?php
            echo $this->grid($this->gridData['idps']['gridConfig']);
        endif;
    endif;
    ?>

    <br/>
    <input id="submit" name="submit" value="Save" type="submit">
    <input id="back" name="back" value="Back" type="button" onclick="location.href='<?php echo $this->listUrl; ?>';">
</form>