<?php $model = $this->virtualOrganisationIdp; ?>

<form id="virtualorganisationidp-edit"
      name="virtualorganisationidp-edit"
      action="<?php echo $this->saveUrl;?>"
      method="POST">

    <input type="hidden" id="vo_id" name="vo_id" value="<?php echo $this->escape($model->vo_id); ?>"/>
    <input type="hidden" id="org_idp_id" name="org_idp_id" value="<?php echo $this->escape($model->idp_id); ?>"/>
    
    <fieldset>
        <?php if (isset($model->errors['idp_id'])): foreach ($model->errors['idp_id'] as $error): ?>
            <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="idp_id">Idp id<span class="required-postfix" title="Required field">*</span></label>
        <input id="idp_id"
               name="idp_id"
               type="text"
               value="<?php echo $this->escape($model->idp_id); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>
    
    <br/>
    <input id="submit" name="submit" value="Save" type="submit">
    <input id="back" name="Back" value="Back" type="button" onclick="location.href='<?php echo $this->listUrl; ?>';">
</form>