<?php $model = $this->groupProvider; ?>

<h2>Group Provider details</h2>

<form id="groupprovider-edit"
      name="groupprovider-edit"
      action="<?php echo $this->saveUrl;?>"
      method="POST">

    <input type="hidden" id="org_group_provider_id" name="org_group_provider_id" value="<?php echo $this->escape($model->group_provider_id); ?>"/>

<?php if ($mode == 'add') : ?>
    <fieldset title="Group Provider Name">
        <?php if (isset($model->errors['group_provider_id'])): foreach ($model->errors['group_provider_id'] as $error): ?>
        <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="group_provider_id">Group Provider name<span class="required-postfix" title="Required field">*</span></label>
        <input id="group_provider_id"
               name="group_provider_id"
               type="text"
               value="<?php echo $this->escape($model->group_provider_id); ?>"
               size="100"
               maxlength="255"
                />

        <p class="hint">
            Only alphanumeric characters, underscores and dashes are allowed.
        </p>
    </fieldset>

    <fieldset title="Group Provider Type">
        <?php if (isset($model->errors['group_provider_type'])): foreach ($model->errors['group_provider_type'] as $error): ?>
        <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label>Group Provider type<span class="required-postfix" title="Required field">*</span></label>
        <input id="group_provider_type_grouper"
               name="group_provider_type"
               type="radio"
               value="GROUPER" <?= $model->group_provider_type === 'GROUPER' ? 'checked' : !isset($model->group_provider_type) ? 'checked'
                : ''; ?>>Group
        <br/>
        <input id="group_provider_type_oauth"
               name="group_provider_type"
               type="radio"
               value="OAUTH" <?= $model->group_provider_type === 'OAUTH' ? 'checked' : ''; ?>>OAuth
    </fieldset>
<?php else : ?>
    <input type="hidden" id="group_provider_id" name="group_provider_id" value="<?php echo $this->escape($model->group_provider_id); ?>"/>
    <input type="hidden" id="group_provider_type" name="group_provider_type" value="<?php echo $this->escape($model->group_provider_type); ?>"/>
    <table class="form_subtable">
        <tr><td class="fieldlabel">Group Provider name:</td></tr><tr><td>&nbsp;<?php echo $this->escape($model->group_provider_id); ?></td></tr>
        <tr><td class="fieldlabel">Group Provider type:</td></tr><tr><td>&nbsp;<?= $model->group_provider_type === 'OAUTH' ? 'OAuth' : 'Grouper' ?></td></tr>
    </table>
    
<?php endif; ?>
    <fieldset title="Adapter">
        <?php if (isset($model->errors['adapter'])): foreach ($model->errors['adapter'] as $error): ?>
        <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="adapter" class="fieldlabel">Adapter</label>
        <input id="adapter"
               name="adapter"
               type="text"
               value="<?php echo $this->escape($model->adapter); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>    

    <fieldset title="Class Name">
        <?php if (isset($model->errors['class_name'])): foreach ($model->errors['class_name'] as $error): ?>
        <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="class_name" class="fieldlabel">Class name<span class="required-postfix" title="Required field">*</span></label>
        <input id="class_name"
               name="class_name"
               type="text"
               value="<?php echo $this->escape($model->class_name); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>    

    <fieldset title="Endpoint">
        <?php if (isset($model->errors['endpoint'])): foreach ($model->errors['endpoint'] as $error): ?>
        <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="endpoint" class="fieldlabel">Endpoint</label>
        <input id="endpoint"
               name="endpoint"
               type="text"
               value="<?php echo $this->escape($model->endpoint); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>    
                
    <fieldset title="Timeout">
        <?php if (isset($model->errors['timeout'])): foreach ($model->errors['timeout'] as $error): ?>
        <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="timeout" class="fieldlabel">Timeout</label>
        <input id="timeout"
               name="timeout"
               type="text"
               value="<?php echo $this->escape($model->timeout); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>    
    <br/>

    <?php if ($model->group_provider_id): ?>
    <a name="decorators"><span class="relationTitle">Decorators</span></a>
    <a href="<?php echo $this->url(array('action' => 'decoratoradd', 'group_provider_id' => $model->group_provider_id)); ?>">Add a new
        Decorator</a>
    <?php
        echo $this->grid($this->gridData['decorators']['gridConfig']);
    ?>
    <br/><br/>

    <a name="preconditions"><span class="relationTitle">Preconditions</span></a>
    <a href="<?php echo $this->url(array('action' => 'preconditionadd', 'group_provider_id' => $model->group_provider_id)); ?>">Add a new
        Precondition</a>
    <?php
        echo $this->grid($this->gridData['preconditions']['gridConfig']);
    ?>
    <br/><br/>

    <a name="groupfilters"><span class="relationTitle">Group Filters</span></a>
    <a href="<?php echo $this->url(array('action' => 'groupfilteradd', 'group_provider_id' => $model->group_provider_id)); ?>">Add a new
        Group Filter</a>
    <?php
        echo $this->grid($this->gridData['group_filters']['gridConfig']);
    ?>
    <br/><br/>

    
    <a name="groupmemberfilters"><span class="relationTitle">Group Member Filters</span></a>
    <a href="<?php echo $this->url(array('action' => 'groupmemberfilteradd', 'group_provider_id' => $model->group_provider_id)); ?>">Add a new
        Group Member Filter</a>
    <?php
        echo $this->grid($this->gridData['group_member_filters']['gridConfig']);
    ?>
    <?php endif; ?>
    <br/>
    <input type="submit" value="Save"></input><input type="button" value="Cancel" onclick="javascript:location.href='<?php echo $this->listUrl;?>'">
</form>
