<?php $model = $this->groupProviderGroupMemberFilter; ?>

<h2>Group Filter details:</h2>
<br/>   
<form id="groupprovidergroupmemberfilter-edit"
      name="groupprovidergroupmemberfilter-edit"
      action="<?php echo $this->saveUrl;?>"
      method="POST">

    <input type="hidden" id="group_provider_id" name="group_provider_id" value="<?php echo $this->escape($model->group_provider_id); ?>"/>
    <input type="hidden" id="org_group_member_filter_id" name="org_group_member_filter_id" value="<?php if ($this->escape($model->group_member_filter_id) != "") : ?><?php echo $this->escape($model->group_member_filter_id); ?><?php else : ?>-1<?php endif; ?>"/>
    <input type="hidden" id="group_member_filter_id" name="group_member_filter_id" value="<?php echo $this->escape($model->group_member_filter_id); ?>"/>
    
    <fieldset>
        <?php if (isset($model->errors['group_member_filter_class_name'])): foreach ($model->errors['group_member_filter_class_name'] as $error): ?>
            <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="url">Class name<span class="required-postfix" title="Required field">*</span></label>
        <input id="group_member_filter_class_name"
               name="group_member_filter_class_name"
               type="text"
               value="<?php echo $this->escape($model->group_member_filter_class_name); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>

    <fieldset>
        <?php if (isset($model->errors['group_member_filter_property'])): foreach ($model->errors['group_member_filter_property'] as $error): ?>
            <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="url">Property<span class="required-postfix" title="Required field">*</span></label>
        <input id="group_member_filter_property"
               name="group_member_filter_property"
               type="text"
               value="<?php echo $this->escape($model->group_member_filter_property); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>

    <fieldset>
        <?php if (isset($model->errors['group_member_filter_replace'])): foreach ($model->errors['group_member_filter_replace'] as $error): ?>
            <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="url">Replace</label>
        <input id="group_member_filter_replace"
               name="group_member_filter_replace"
               type="text"
               value="<?php echo $this->escape($model->group_member_filter_replace); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>

    <fieldset>
        <?php if (isset($model->errors['group_member_filter_search'])): foreach ($model->errors['group_member_filter_search'] as $error): ?>
            <div class="form-error"><?php echo $error; ?></div>
        <?php endforeach; endif; ?>
        <label for="url">Search</label>
        <input id="group_member_filter_search"
               name="group_member_filter_search"
               type="text"
               value="<?php echo $this->escape($model->group_member_filter_search); ?>"
               size="100"
               maxlength="255"
                />
    </fieldset>

    <br/>
    <input id="submit" name="submit" value="Save" type="submit">
    <input id="back" name="back" value="Back" type="button" onclick="location.href='<?php echo $this->listUrl; ?>#groupmemberfilters';">
</form>