<?php echo $this->doctype() ?>
<html lang="nl">
    <head>
        <meta charset="utf-8" />
        <title>SURFconext Platform Administration Environment</title>
        <?php 
            echo $this->headLink()->appendStylesheet('/css/reset.css')
                                  ->appendStylesheet('/css/fonts.css')
                                  ->appendStylesheet('/css/global.css')
                                  ->appendStylesheet('/css/boxes.css'); 
                                    
                  
            echo $this->headScript(); 
            echo $this->headStyle();
            
        ?>

        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/fonts/fonts-min.css" />
        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/paginator/assets/skins/sam/paginator.css" />
        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/datatable/assets/skins/sam/datatable.css" />
        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/menu/assets/skins/sam/menu.css" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/yahoo-dom-event/yahoo-dom-event.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/container/container_core-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/menu/menu-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/connection/connection-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/yahoo/yahoo-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/event/event-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/json/json-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/element/element-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/datasource/datasource-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/datatable/datatable-min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/yui/2.8.2r1/build/paginator/paginator-min.js"></script>

        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body class="yui-skin-sam">
        <header>
            <div class="nav" id="TopNav"></div>
            <a href="/" id="Logo"><img src="/media/logo-surfnet.gif" alt="SURFNET - We make innovation work"></a>
        </header>

        <nav>
            <?php echo $this->navigation();?>
        </nav>
        <div class='content'>
            <?php echo $this->layout()->content ?>
        </div>
        
        <footer>
            <?php echo $this->inlineScript() ?>
        </footer>
    </body>
</html>
